voter/urls.py
from django.urls import include, path


from .views import *

urlpatterns = [
    path("", list_items, name="list_voters"),
]

voter_influencer/users/urls.py
from django.urls import path

from voter_influencer.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

partyworker/models.py
from voter_influencer.users.models import User
from django.db import models
from django.db.models.deletion import RESTRICT
from enum import Enum

from voter.models import Caste
from django.conf import settings

# Create your models here.

class WorkerType(models.Model):
    title = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self) -> str:
        return self.title

class PartyWorker(models.Model):
    user = models.OneToOneField(User, on_delete=RESTRICT)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=settings.GENDERS, null=True, blank=True)
    worker_type = models.ForeignKey(WorkerType, related_name='workers', on_delete=RESTRICT)
    caste = models.ForeignKey(Caste, related_name='workers', on_delete=RESTRICT)
    category = models.CharField(max_length=20, choices=settings.CATEGORIES, null=True, blank=True)
    mobile = models.BigIntegerField(null=True, blank=True)
    photo = models.FileField(null=True, blank=True)
    points = models.IntegerField(default=0)
    address = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return self.user.username

voter/models.py
from django.db import models
from django.db.models.deletion import RESTRICT
from django.db.models.fields import CharField
from enum import Enum
from django.conf import settings

from voter_influencer.users.models import User
# Create your models here.
from polling_station.models import PollingStationImage, PollingStation



class VoterImage(models.Model):
    polling_station = models.ForeignKey(PollingStation, related_name='voter_images', on_delete=RESTRICT)
    station_image = models.ForeignKey(PollingStationImage, related_name='voter_images', on_delete=RESTRICT)
    image = models.FileField(null=True, blank=True)
    image_url = models.FileField(null=True, blank=True)
    x = models.IntegerField(default=0)
    y = models.IntegerField(default=0)
    w = models.IntegerField(default=0)
    h = models.IntegerField(default=0)
    is_cropped = models.BooleanField(default=False)
    is_voter_id_captured = models.BooleanField(default=False)
    is_photo_captured = models.BooleanField(default=False)
    is_serial_captured = models.BooleanField(default=False)
    is_details_captured = models.BooleanField(default=False)
    is_processed = models.BooleanField(default=False)
    has_errors = models.BooleanField(default=False)
    md5_signature = models.CharField(max_length=1000, unique=True)
    
    def __str__(self) -> str:
        return self.image.url



class Caste(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=20, choices=settings.CATEGORIES)
    related_surnames = models.TextField()

    def __str__(self) -> str:
        return self.title + " - " + self.category




class Voter(models.Model):
    md5_signature = models.CharField(max_length=1000, unique=True)
    voter_id = models.CharField(max_length=20, null=True, blank=True)  # Primary Key, Unique
    serial_number = models.IntegerField(null=True, blank=True)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    father_name = models.CharField(max_length=100, null=True, blank=True)
    husband_name = models.CharField(max_length=100, null=True, blank=True)
    age = models.SmallIntegerField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=settings.GENDERS, null=True, blank=True)
    house_number = models.CharField(max_length=20, null=True, blank=True)
    caste = models.ForeignKey(Caste, related_name='voters', on_delete=RESTRICT, null=True, blank=True)
    category = models.CharField(max_length=20, choices=settings.CATEGORIES, null=True, blank=True)
    mobile = models.CharField(max_length=15, null=True, blank=True)

    data_eng = models.TextField(null=True, blank=True)
    data_hin = models.TextField(null=True, blank=True)

    polling_booth = models.ForeignKey(PollingStation, related_name='voters', on_delete=RESTRICT)
    polling_station_image = models.ForeignKey(
        PollingStationImage, related_name='voters', on_delete=RESTRICT)
    voter_image = models.ForeignKey(VoterImage, related_name='voters', on_delete=RESTRICT)

    class Meta:
        ordering = ('polling_booth', 'house_number',)

    def __str__(self) -> str:
        return self.md5_signature

voter_influencer/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for voter-influencer."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

voter_influencer/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

voter_influencer/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

voter_influencer/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

voter_influencer/templates/worker/add_worker.html
{% extends "base.html" %}


{% block page_title %}
<h1>
    Add Worker
</h1>    
{% endblock page_title %}


{% block search_bar %}
<form method="POST" action="{% url 'list_workers' %}">
    {% csrf_token %}
    <input type="text" name="booth_id" />

    <select class="dropdown">
        <option>-- All --</option>
    {% for worker_type in worker_types %}
        <option id="{{worker_type.id}}">{{worker_type.title}}</option>
    {% endfor %}
    </select>

    <button class="btn btn-primary">Search</button>
</form>
{% endblock search_bar %}


{% block toolbar %}

    <a href="{% url 'add_worker' %}" class="btn btn-primary">Add</a>

{% endblock toolbar %}



{% block content %}

<form enctype="multipart/form-data" method="post" id="partyworker_form">
    {% csrf_token %}
      <fieldset class="module aligned ">
           
        <div class="form-group">
            <div>
                <label for="id_mobile">Mobile:</label>
                <input type="number" name="mobile" id="id_mobile" required>
            </div>
        
            </div>
        
            <div class="form-group">
                    <div>
                            <label for="id_full_name">Full name:</label>
                                <input type="text" name="full_name" class="vTextField" maxlength="100" id="id_full_name" required="True">
                    </div>
            </div>
        
            <div class="form-row field-gender">
                
                
                <div class="form-group">
                    <label for="id_gender">Gender:</label>
                    <select name="gender" id="id_gender" required>
                        <option value="" selected="">---------</option>
                        <option value="MALE">MALE</option>
                        <option value="FEMALE">FEMALE</option>
                        <option value="OTHER">OTHER</option>
                    </select>
                </div>
            </div>
        
            <div class="form-group">
                <div>
                    <label class="required" for="id_worker_type">Worker type:</label>
                    
                    <div class="related-widget-wrapper">
                        <select name="worker_type" required id="id_worker_type" >
                            <option value="" selected="">---------</option>
                            {% for worker_type in worker_types %}
                            <option value="{{worker_type.id}}" selected="">{{worker_type.title}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div>
                    <label class="required" for="id_caste">Caste:</label>
                            
                        <div class="related-widget-wrapper">
                            <select name="caste" required id="id_caste">
                                 <option value="" selected="">---------</option>
                                 {% for caste_name in caste_names %}
                                 <option value="{{caste_name.id}}" selected="">{{caste_name.title}}</option>
                                {% endfor %}
    
                            </select>
        
                        </div>
                </div>
            </div>
             
        
        
    </fieldset>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <input type="submit" value="Save" class="default" name="_save">
    
    
    </form>

{% endblock content %}

voter_influencer/templates/worker/edit_worker.html
{% extends "base.html" %}


{% block page_title %}
<h1>
    Edit Worker
</h1>    
{% endblock page_title %}


{% block search_bar %}
<form method="POST" action="{% url 'list_workers' %}">
    {% csrf_token %}
    <input type="text" name="booth_id" />

    <select class="dropdown">
        <option>-- All --</option>
    {% for worker_type in worker_types %}
        <option id="{{worker_type.id}}">{{worker_type.title}}</option>
    {% endfor %}
    </select>

    <button class="btn btn-primary">Search</button>
</form>
{% endblock search_bar %}


{% block toolbar %}

    <a href="{% url 'add_worker' %}" class="btn btn-primary">Add</a>

{% endblock toolbar %}



{% block content %}

<form method="POST" id="partyworker_form" >
    {% csrf_token %}
      <fieldset class="module aligned ">
           
        <div class="form-group">
            <div>
                <label for="id_mobile">Mobile:</label>
                {{worker.mobile}}
            </div>
        
            </div>
        
            <div class="form-group">
                    <div>
                            <label for="id_full_name">Full name:</label>
                                <input type="text" name="full_name" class="vTextField" value="{{worker.full_name}}" maxlength="100" id="id_full_name">
                    </div>
            </div>
        
            <div class="form-row field-gender">
                
                
                <div class="form-group">
                    <label for="id_gender">Gender:</label>
                    <select name="gender" id="id_gender">
                        <option value="" selected="">---------</option>
                        <option value="MALE" {% if worker.gender == "MALE" %}selected{% endif %} >MALE</option>
                        <option value="FEMALE" {% if worker.gender == "FEMALE" %}selected{% endif %}>FEMALE</option>
                        <option value="OTHER" {% if worker.gender == "OTHER" %}selected{% endif %}>OTHER</option>
                    </select>
                </div>
            </div>
        
            <div class="form-group">
                <div>
                    <label class="required" for="id_worker_type">Worker type:</label>
                    
                    <div class="related-widget-wrapper">
                        <select name="worker_type" required="" id="id_worker_type">
                            <option value="" selected="">---------</option>
                            {% for worker_type in worker_types %}
                            <option value="{{worker_type.id}}" {% if worker.worker_type.id == worker_type.id %}selected{% endif %}>{{worker_type.title}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div>
                    <label class="required" for="id_caste">Caste:</label>
                            
                        <div class="related-widget-wrapper">
                            <select name="caste" required="" id="id_caste">
                                 <option value="" selected="">---------</option>
                                 {% for caste_name in caste_names %}
                                 <option value="{{caste_name.id}}" {% if worker.caste.id == caste_name.id %}selected{% endif %}>{{caste_name.title}}</option>
                                {% endfor %}
    
                            </select>
        
                        </div>
                </div>
            </div>
             
        
        
    </fieldset>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <input type="submit" value="Save" class="default" name="_save">
    
    
    </form>

{% endblock content %}

voter_influencer/templates/worker/workers.html
{% extends "base.html" %}


{% block page_title %}
<h1>
    Workers
</h1>    
{% endblock page_title %}


{% block search_bar %}
<form method="POST" action="{% url 'list_workers' %}">
    {% csrf_token %}
    <input type="text" name="booth_id" />

    <select class="dropdown">
        <option>-- All --</option>
    {% for worker_type in worker_types %}
        <option id="{{worker_type.id}}">{{worker_type.title}}</option>
    {% endfor %}
    </select>

    <button class="btn btn-primary">Search</button>
</form>
{% endblock search_bar %}


{% block toolbar %}

    <a href="{% url 'add_worker' %}" class="btn btn-primary">Add</a>

{% endblock toolbar %}



{% block content %}

<table class="table">
    <th>Name</th>
    <th>Mobile</th>
    <th>Type</th>
    <th>Gender</th>
    <th>Actions</th>
    <tbody>
        {% for worker in workers %}
        <tr>
            <td>{{worker.full_name}}</td>
            <td>{{worker.mobile}}</td>
            <td>{{worker.worker_type}}</td>
            <td>{{worker.gender}}</td>
            <td><a href="{% url 'update_worker' worker.id %}">Edit</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}